---
title: "p8105_hw1_jo2570"
author: "Jai Oberoi"
date: "17/09/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#run tidyverse package and create a data frame called hw1_df with 4 different types of variables 
library(tidyverse)

set.seed(9)

hw1_df = tibble( 
  samp = rnorm(8), 
  vec_logical = samp > 0,
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h"),
  vec_factor = factor(c("newyork", "boston", "atlanta", "newyork", "boston", "atlanta", "newyork", "boston"))
)

#attempting to take the mean of each variable in data frame hw1_df 

#mean of the random normal sample, samp: 
mean(pull(hw1_df, samp))
#we can get a mean value for the variable samp as it is a numerical vector 

#mean of the variable vec_logical
mean(pull(hw1_df, vec_logical))  
#we can get a mean value for vec_logical 
    
#mean of the variable vec_char
mean(pull(hw1_df, vec_char))  
#we cannot take the mean of vec_char - we get an error saying that the argument is not numeric or logical and the result returns NA 

#mean of the variable vec_factor
mean(pull(hw1_df, vec_factor)) 
#we cannot take the mean of vec_factor - we get an error saying that the argument is not numeric or logical and the result returns NA 

```


```{r eval = FALSE}
#converting vec_logical to a numeric vector 
as.numeric(pull(hw1_df, vec_logical))

#coverting vec_char to a numeric vector 
as.numeric(pull(hw1_df, vec_char))

#converting vec_factor to a numeric vector 
as.numeric(pull(hw1_df, vec_factor))


#we see (from the console) that the logical vector gets converted into a binary numeric vector (FALSE = 0 and TRUE = 1)
#the character vector is not able to convert to a numeric vector but is forced to give a vector of NA values of the same length 
#the factor vactor is coverted to a numeric vector with 3 numers (1, 2, 3) representing the factor levels 

```


```{r}
#converting vec_logical to a numeric vector and then multiplying the result by samp
as.numeric(pull(hw1_df, vec_logical))*(pull(hw1_df, samp))

#converting vec_logical to a numeric vector and then multiplying the result by samp
as.factor(pull(hw1_df, vec_logical))*(pull(hw1_df, samp))

#converting vec_logical to a factor vector, then converting the result into a numeric and then multiplying by the random normal samp 
as.factor(pull(hw1_df, vec_logical))
as.numeric(as.factor(pull(hw1_df, vec_logical)))*(pull(hw1_df, samp))

```



```{r}
#problem 2 

#creating a new data frame called hw1_df2 
set.seed(999)
hw1_df2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  vec_logical2 = x + y > 1,
  vec_numeric = as.numeric(vec_logical2),
  vec_factor2 = as.factor(vec_logical2)
  )     

```

the size of the dataframe `hw1_df2` is `r nrow(hw1_df2)` rows and `r ncol(hw1_df2)` columns
mean of x = `r mean(pull(hw1_df2, x))`, 
median = `r median(pull(hw1_df2, x))`, 
standard deviation = `r sd(pull(hw1_df2, x))` 
proportion of cases for which x + y > 1 = `r mean(pull(hw1_df2, vec_logical2))`

